apiVersion: v1
kind: Service
metadata:
  name: {{ include "back_chart.fullname" . }}
  labels:
    {{- include "back_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.app.port }}
      targetPort: {{ .Values.service.ports.app.targetPort }}
      protocol: {{ .Values.service.ports.app.protocol }}
      name: http
  selector:
    {{- include "back_chart.selectorLabels" . | nindent 4 }}
