pipeline {
    agent {
        label 'elad-labs'
    }

    environment {
        registry = "shlomihaimov1/front:latest"
        registryCredential = 'dockerhub'
        imageName = "front:latest"
        dockerImage = ''
        dockerfilePath = 'front/my-app'
    }

    stages {
        stage('Init') {
            steps {
                echo 'Initializing..'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        // stage('Checkout') {
        //     steps {
        //         echo 'Cloning Git..'
        //         git 'https://github.com/shlomihaimov1/do_proj1.git'
        //     }
        // }
        // stage('Test') {
        //     steps {
        //         echo 'Testing..'
        //         echo 'Running pytest..'
        //     }
        // }
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    try {
                        dockerImage = docker.build(registry, dockerfilePath) 
                    } catch (Exception e) {
                        echo "Error during Docker build: ${e.message}"
                        throw e
                    }
                }
            }
        }
        stage('Publish') {
            steps {
                echo 'Publishing..'
                // script {
                //     docker.withRegistry( '', registryCredential ) {
                //         dockerImage.push()
                //     }
                // }
                script {
                    dockerImage.push()
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
                
            }
        }
        stage('Cleanup') {
            steps {
                echo 'Cleaning..'
                // sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}