pipeline {
    agent any

    environment {
        registry = "shlomihaimov1"
        registryCredential = 'dockerhub'
        imageName = "front:latest"
        dockerImage = ''
        dockerfilePath = '/front/my-app/Dockerfile'
    }

    stages {
        stage('Init') {
            steps {
                echo 'Initializing..'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        // stage('Checkout') {
        //     steps {
        //         echo 'Cloning Git..'
        //         git 'https://github.com/shlomihaimov1/do_proj1.git'
        //     }
        // }
        // stage('Test') {
        //     steps {
        //         echo 'Testing..'
        //         echo 'Running pytest..'
        //     }
        // }
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    try {
                        // dockerImage = docker.build("front:${env.BUILD_ID}",
                        //            "-f Dockerfile ${dockerfilePath}")
                        dockerImage = docker.build("${imageName}", "${dockerfilePath}") 
                        // // docker.build("--file ${dockerfilePath}", "${registry}:$BUILD_NUMBER")
                        // docker.withRegistry("${registryCredential}", 'credentials-id') {

                        //     def customImage = docker.build("my-image:${env.BUILD_ID}")

                        //     /* Push the container to the custom Registry */
                        //     customImage.push()
                        // }
                        // sh "docker build -t ${registry}/${imageName} -f ${dockerfilePath} ."
                    } catch (Exception e) {
                        echo "Error during Docker build: ${e.message}"
                        throw e
                    }
                }
            }
        }
        stage('Publish') {
            steps {
                echo 'Publishing..'
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
                
            }
        }
        stage('Cleanup') {
            steps {
                echo 'Cleaning..'
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}