pipeline {
    agent {
        label 'elad-labs'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    environment {
        registry = "shlomihaimov1/front:latest"
        registryCredential = credentials('dockerhub')
        dockerfilePath = 'front/my-app'
    }

    stages {
        stage('Init') {
            steps {
                echo 'Initializing..'
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
        }
        // stage('Test') {
        //     steps {
        //         echo 'Testing..'
        //         echo 'Running pytest..'
        //     }
        // }
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    try {
                        dockerImage = docker.build(registry, dockerfilePath) 
                    } catch (Exception e) {
                        echo "Error during Docker build: ${e.message}"
                        throw e
                    }
                }
            }
        }
        stage('Publish') {
            steps {
                echo 'Publishing..'
                script {               
                    try {
                        // docker.withRegistry('https://index.docker.io/v1/', 'DOCKER_HUB') {
                        //     dockerImage.push()
                        // }
                        docker.withRegistry( '', registryCredential ) {
                            dockerImage.push()
                        }
                    } catch (Exception e) {
                        echo "Error during Docker build: ${e.message}"
                        throw e
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
                
            }
        }
        stage('Cleanup') {
            steps {
                echo 'Cleaning..'
                // sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}